### ISSUE TITLE
Output items validation (mimiciii)

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#10]
On eicu we excluded patients based on the amount of output gastric >= 500 OR stool >= 500 OR emesis >= 500

These are the items I found on the table _outputevents_ in mimiciii, are they all looking like the ones we are interested in exlcluding or are any of them not looking right?
 
| Output Item              |
|--------------------------|
| Stool Out Rectal Tube    |
| Stool Out Fecal Bag      |
| Stool Out Ileostomy      |
| Stool .                  |
| Gastric Gastric Tube     |
| Stool Out Ostomy         |
| Stool Out (non-specific) |
| Stool Out Colostomy      |
| Stool Out Other          |
| Oral Gastric             |
| Gastric Emesis           |
| Gastric Other            |
| stool cc/kg/hr           |
| Gastric Tube             |
| Gastric Jejunostomy Tube |
| Nasogastric              |
| Stool                    |
| Emesis                   |
| emesis                   |
| Anderson (gastric)       |
| PACU Gastric             |
| Gastric lavage           |
| gastric                  |
| OR Stool/NGT             |
| gastric Ph               |
| GASTRIC ASPIRATION       |
| stool/fistula            |
| epi. of stool incont     |
| gastric lavage           |
| EMESIS                   |
| Gastric Blakemore        |
| Gastric Ewald            |
| stool                    |
| GASTRIC OUT              |
| OR EMESIS                |
| Blood emesis             |
| farr 5 emesis            |
| GASTRIC RESIDUAL         |
| Gastric aspirate         |
| PACU EMESIS              |
| gastric asp              |
| Flexiseal stool          |
| Gastric Nasogastric      |
| Stool Out Stool          |
| Gastric Oral Gastric     |
| Stool out                |
| gastric output           |

Thanks!

**Comment by gwendolynglee** [comment]
looks good

**Comment by theonesp** [comment]
thanks!
