### ISSUE TITLE
Fix quantile imputation

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#14]
https://github.com/theonesp/vol_leak_index/blob/da5419d861593aca461423e4e293886d078b8486/eicu_vli/analysis/01_dataset_creation.Rmd#L304

Jay can you please finish this line?, I am trying to apply median imputation to everything avobe .95 and below .5 centile.
And then see how the model looks

**Comment by jaychandra3** [comment]
Fixed this and pushed the code
