### ISSUE TITLE
snuh_vli 01_dataset_creation or 01_dataset_creation_new ?

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#15]
https://github.com/theonesp/vol_leak_index/blob/5067ea8f2374ae7baecaecf2e9c5d9243f8b2a91/snuh_vli/01_dataset_creation.Rmd#L2

In snuh_vli we have 01_dataset_creation & 01_dataset_creation_new, which one should be removed?

**Comment by jaychandra3** [comment]
I removed the 01_dataset_creation and renamed 01_dataset_creation_new as 01_dataset_creation
