### ISSUE TITLE
intake data

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#7]
https://github.com/theonesp/vol_leak_index/blob/37dba956b5dd08ce448c1b41ae14dadf1e42732a/eicu/analysis/sql/intake.sql#L6
@jaychandra3 could you please have a look at this query, it is only extracting intake data from _infusiondrug_ but we need also data from _intakeoutput_, did we decide we were only addressing one of the tables or both of them together?

I have already filtered by _only reliable fluid data_

Thanks!

**Comment by jaychandra3** [comment]
I remember why we didn’t use intakeoutput. The data entry was extremely noisy and there is no good way to extract the data. A few of the other files that are now deleted experimented with inatekouput but the results were not clean. We consulted with Alistair and Leo and they were okay with just using infusion drug.
