### ISSUE TITLE
Revise bleeding categories (mimiciii)

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#8]
Could you please revise whether bleeding categories make sense?
https://github.com/theonesp/vol_leak_index/blob/9275c70d9c1a55b128d6b9a80a868ff2e2938098/mimic_vli/analysis/sql/patient_inexcluded_icd9.sql#L11

**Comment by gwendolynglee** [comment]
probably don't have to exclude postmenopausal bleeding, but that likely has very few cases anyway

**Comment by theonesp** [comment]
excluded from the icd list, thanks!
