### ISSUE TITLE
Output blood valiadation (eicu)

### ISSUE THREAD

**Issue by theonesp** [theonesp/cap_leak_index#9]
https://github.com/theonesp/vol_leak_index/blob/9275c70d9c1a55b128d6b9a80a868ff2e2938098/eicu_vli/analysis/sql/IO_exclusion.sql#L15 
The way this query is writen we are excluding patients in any of these categories regardless of the amount. Is this correct?

|I/O |  (ml)               | Item                |
|-------------|-----------------------------------|--------------------------------------------------|
| Intake (ml) | Blood Products (ml)               | Volume-Transfuse red blood cells                 |
| Intake (ml) | Blood Products (ml)               | Volume-Transfuse platelet pheresis               |
| Intake (ml) | Blood Products (ml)               | PRBC                                             |
| Intake (ml) | Blood Products (ml)               | Volume-Transfuse plasma                          |
| Intake (ml) | Blood Products (ml)               | Albumin Intake                                   |
| Intake (ml) | Blood Products (ml)               | pRBCs                                            |
| Intake (ml) | Blood Products (ml)               | FFP                                              |
| Intake (ml) | Blood Products (ml)               | Cell Saver                                       |
| Intake (ml) | Blood Products (ml)               | Platelets                                        |
| Output (ml) | Blood Loss                        |                                                  |
| Intake (ml) | Blood Products (ml)               | Volume-Transfuse cryoprecipitate                 |
| Intake (ml) | Blood Products (ml)               | Mass Transfusion Volume                          |
| Output (ml) | SN Total Blood Product Volume(ml) |                                                  |
| Output (ml) | SN Blood Loss(ml)                 |                                                  |
| Intake (ml) | Generic Intake (ml)               | NS for Blood Administration                      |
| Intake (ml) | Blood Products (ml)               | Volume (ml)-Transfuse Cryoprecipitate            |
| Intake (ml) | Blood Products (ml)               | Volume (ml)-Transfuse - Cryoprecipitate          |
| Intake (ml) | Blood Products (ml)               | Volume (ml)-Transfuse - Leukoreduced Packed RBCs |
| Intake (ml) | Blood Products (ml)               | Cryoprecipitate                                  |
| Intake (ml) | Blood Products (ml)               | Blood Products                                   |
| Intake (ml) | Blood Products (ml)               | Cryo Infused                                     |
| Intake (ml) | Blood Products (ml)               | Other Blood Prod                                 |
| Output (ml) | Blood (non-drain)                 |                                                  |
| Output (ml) | Estimated Blood Loss              |                                                  |

**Comment by gwendolynglee** [comment]
looks good!

**Comment by theonesp** [comment]
thanks!
